### ISSUE TITLE
Merging won't let keep variables of same name from different tables, even though renamed

### ISSUE THREAD

**Issue by JKoltsov** [redivis/help#13]
I am working now with the new version and am having issues with merges that worked previously.  If I have two svcdate variables (for example), one each from the t0 (the date if the index surgery) and t1 (the date of the readmission or outpatient service rendered to that same patient on a different day) datasets, it is not letting me keep both, even though I have renamed one.  I.e. I renamed the t0 svcdate as SVCDATE_index, but it still for some reason thinks both are named svcdate.  It will not let me compile any of my merges!

**Comment by imathews** [comment]
Hi @JKoltsov — sorry about that, this is likely a bug. We'll have a fix out shortly; will update here

**Comment by JKoltsov** [comment]
Also,  I created a variable "TimeFromIndex" and then wanted to filter by TimeFromIndex <=90 in the same transform, and in the filter it gives me an error saying "TimeFromIndex no longer exists" even though I created the variable and have it in the list of variables to output.

**Comment by JKoltsov** [comment]
The weird thing is it isn't giving me this error on one project, but it is giving me this error on another on basically the same data step  (one merges outpatient with inpatinet data, one merges outpatient with outpatient data).

**Comment by JKoltsov** [comment]
Also, the "export table" button seems to have reverted again and no longer shows the spinning wheel as it is preparing the table for export (nothing happens so you don't know if it is working on it or if you didn't click right.)

**Comment by imathews** [comment]
Hi @JKoltsov this is now fixed. This bug was temporarily introduced with a small update yesterday.

Let us know if you run into any further issues!

**Comment by imathews** [comment]
@JKoltsov Sorry I didn't see these other comments when I closed — the export  issue is known and will be resolved comprehensively next week. As for the first issue, could you share the relevant project with me and point me to where this is happening?

**Comment by imathews** [comment]
actually we've been able to recreate this. a fix is in the works...

**Comment by imathews** [comment]
A fix for the new variable comparisons is being deployed now, and should be live within 10 minutes
