### ISSUE TITLE
Question on filtering

### ISSUE THREAD

**Issue by JKoltsov** [redivis/help#20]
Hi!  One of my filters worked in a way that I didn't expect and I was curious as to why/if I did something wrong on my end with the logic.

I had the following filter for the Truven outpatient services:
Filter by
proc1 = list of 3 procedure codes AND
any of dx1, dx2, dx3, dx4 = list of 9 diagnoses codes

When I ran this, I ended up with over 11 million records for 5 million unique patients.  This is way too many.

However, when I split the filtering step to first do the transform:
Filter by proc1 = list of 3 procedure codes

and then in a separate tranform:
Filter by dx1, dx2, dx3, dx4 = list of 9 diagnoses codes

Then I get ~200k records for roughly 134k patients, which is what I should have.

Why did filtering for those two things with the AND logic not work? I was getting a ton of different procedure codes that weren't in my list of 3.

**Comment by imathews** [comment]
Hi @JKoltsov would you be able to point me towards a reproducible case for this? We'll work to get to sort out what might be going on

**Comment by imathews** [comment]
Thanks @JKoltsov — we've been able to recreate this; it was an important find. In the case you described, we weren't properly parenthesizing the query, which caused the logic statement to behave differently from what would be expected.

We'll have a fix out asap.

**Comment by imathews** [comment]
This should now be resolved. Thanks again for letting us know

**Comment by JKoltsov** [comment]
Great.  Glad I could help!
