### ISSUE TITLE
Export button not working at all - Work stoppage

### ISSUE THREAD

**Issue by JKoltsov** [redivis/help#22]
Hi--I exported one data set from my tree at 11:06 this morning, and subsequently clicking export is doing nothing.  I have a few data sets that are over the size allowance, and these still me the appropriate error when I try to click export.  The ones that are not over the size limit are doing nothing when I click the export button. Help!  (Also, again, it was much nicer when the export button predicted the size in gigs of the data export and showed a spinning icon when it was processing.)

**Comment by JKoltsov** [comment]
Okay, I logged out and shut my browser.  After reopening and logging back in, I can now export.  Don't know what happened...

**Comment by JKoltsov** [comment]
Just had the same thing happen again...same fix solved it.

**Comment by imathews** [comment]
Hi @JKoltsov — the new table exports UI will go out this week, and should solve these issues. Sorry that you ran into this.

Did you try to do a hard reload of the page? (cmd + R or "reload" button) That might work as well as a temporary solution.

Also, unrelated — this repo is intended more for issues / todo's in our help documentation (though I understand this could be confusing). We're more likely to see issues that are posted in https://github.com/redivis/meta, if you want to put future issues / feature requests / etc. in there.

But thanks for opening these issues! It's very helpful for us to identify any bugs and promptly address user needs.
